# serverless.yml
# by Preston Hager

service: scoreboard
app: scoreboard
org: prestonhager

frameworkVersion: '2'

package:
  exclude:
    - '**'
  include:
    - '!./**'
    - handler.py
    - errors.json
    - templates/**
    - lib/**
    - static/**

provider:
  name: aws
  runtime: python3.8
  region: us-west-2
  lambdaHashingVersion: 20201221
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: arn:aws:dynamodb:*:*:table/scoreboard-*

functions:
  index:
    handler: handler.index
    events:
      - http:
          method: GET
          path: '/'
  edit:
    handler: handler.edit
    events:
      - http:
          method: GET
          path: edit
  auth:
    handler: handler.auth
    events:
      - http:
          method: POST
          path: auth
  add_listing:
    handler: handler.add_listing
    events:
      - http:
          method: POST
          path: add-listing
  edit_listing:
    handler: handler.edit_listing
    events:
      - http:
          method: POST
          path: edit-listing
  edit_scoreboard:
    handler: handler.edit_scoreboard
    events:
      - http:
          method: POST
          path: edit-scoreboard
  delete_listing:
    handler: handler.delete_listing
    events:
      - http:
          method: POST
          path: delete-listing
  static:
    handler: handler.static
    events:
      - http:
          method: GET
          path: static/{filename}

plugins:
  - serverless-domain-manager
  - serverless-python-requirements
  - serverless-offline
custom:
  serverless-offline:
    noPrependStageInUrl: 1
  # Modify the following variables to change the domain name and subdomain
  # you can also change the base path and more down below in the customDomain poriton
  appDomain: 'prestonhager.xyz'
  subdomain: scoreboard
  # If you commented out the serverless-python-requirements line, comment out this too
  pythonRequirements:
    dockerizePip: true
  # If you commented out the serverless-domain-manager line, comment out this too
  customDomain:
    domainName: ${self:custom.subdomain}.${self:custom.appDomain}
    basePath: ''
    stage: ${self:provider.stage, 'dev'}
    certificateName: ${self:custom.appDomain}
    createRoute53Record: false
