# serverless.yml
# by Preston Hager

service: scoreboard
app: scoreboard
org: prestonhager

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  region: us-west-2
  lambdaHashingVersion: 20201221
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
      Resource: arn:aws:dynamodb:*:*:table/scoreboard-scoreboards

functions:
  index:
    handler: handler.index
    events:
      - http:
          method: GET
          path: '/'
  auth:
    handler: handler.auth
    events:
      - http:
          method: POST
          path: auth
  add_listing:
    handler: handler.add_listing
    events:
      - http:
          method: POST
          path: add-listing
  edit_listing:
    handler: handler.edit_listing
    events:
      - http:
          method: POST
          path: edit-listing
  static:
    handler: handler.static
    events:
      - http:
          method: GET
          path: static/{filename}

plugins:
  # If not using the custom domain then comment out the next line
  - serverless-domain-manager
  # If you're on linux and wish to not use docker for compiling, comment out the next line
  - serverless-python-requirements
custom:
  # Modify the following variables to change the domain name and subdomain
  # you can also change the base path and more down below in the customDomain poriton
  appDomain: 'prestonhager.xyz'
  subdomain: scoreboard
  # If you commented out the serverless-python-requirements line, comment out this too
  pythonRequirements:
    dockerizePip: true
  # If you commented out the serverless-domain-manager line, comment out this too
  customDomain:
    domainName: ${self:custom.subdomain}.${self:custom.appDomain}
    basePath: ''
    stage: ${self:provider.stage, 'dev'}
    certificateName: ${self:custom.appDomain}
    createRoute53Record: false
